// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_KlIQsVpm7TA01slO2OrGEkK1YsQG3M',
    appId: '1:73454248201:android:f765a35e22f90bd375f3d8',
    messagingSenderId: '73454248201',
    projectId: 'booklib-51e64',
    storageBucket: 'booklib-51e64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_8XAZtT4nlZibU8mkEfary6xGX4Wnb_I',
    appId: '1:73454248201:ios:3a38ff847dd36aaf75f3d8',
    messagingSenderId: '73454248201',
    projectId: 'booklib-51e64',
    storageBucket: 'booklib-51e64.appspot.com',
    iosClientId: '73454248201-rr5hsmecr43me6dqjsg83d9jb79fo5nl.apps.googleusercontent.com',
    iosBundleId: 'qfeljnac',
  );
}
